name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100

    - name: Pack
      run: dotnet pack YoutubeExplode.Converter --configuration Release

    - name: Deploy
      run: dotnet nuget push YoutubeExplode.Converter/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
